### ISSUE TITLE
.husky/commit-msg: 2: .: Can't open .husky/_/husky.sh

### ISSUE THREAD

**Issue by trueblood12** [typicode/husky#1078]
We are using _Husky_ with _Commitlint_ and _Commitizen_ in a Windows development environment (with WSL). Using the terminal (Hyper + OhMyZsh + zsh, when we run our commit script and walk through the _Commitizen_ prompts, our linting and testing work, but when the `commit-msg` appears to get invoked, we get the error message `.husky/commit-msg: 2: .: Can't open .husky/_/husky.sh`.

```
...
"@commitlint/cli": "^14.1.0",
"@commitlint/config-conventional": "^14.1.0",
"cz-conventional-changelog": "3.3.0",
"husky": "^7.0.4",
"lint-staged": "^11.2.6",
...
```

We have **husky**, **lint-staged**, **commitlint** and **config** setup in _package.json_:

```
"husky": {
    "hooks": {
      "_pre-push": "lint-staged && yarn test",
      "pre-commit": "lint-staged",
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  },
  "lint-staged": {
    "./src/components/**/*.js, ./src/screens/**/*.js": "eslint --fix"
  },
  "commitlint": {
    "extends": [
      "@commitlint/config-conventional"
    ]
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  },
```

Here are some of our **scripts**:
```
...
"android": "expo run:android",
"ios": "expo run:ios",
"web": "expo start --web",
"start": "react-native start",
"lint": "npx eslint ./src/screens/**/*.js ./src/components/**/*.js",
"pre-commit": "lint-staged",
"commit": "cz",
"test": "jest",
"test:clearCache": "jest --clearCache",
"test:coverage": "jest --coverage",
"test:watch": "jest --watchAll",
"prepare": "husky install"
 ...
 ```
I wanted to note that we have used the following: `"pre-commit": "npx lint-staged"`, but this had no effect.

Blowing out `.git/hooks` and `node_modules` and reinstalling pages, also had no effect.

**Comment by ramesius** [comment]
I think I found the issue here after experiencing it myself.

The `.gitignore` file that `husky` places into `.husky/_` ignores everything in the same directory. This results in an empty directory from the perspective of the `git` tree. When `git` performs a `git stash` operation it prunes empty directories from its tree.
Adding a `.gitkeep` and committing that to the tree resolves the issue, however I think this should be resolved in `husky` itself.

Two solutions that `husky` could adopt:
- Have the `.gitignore` file include `!.gitignore` and commit the file to the git tree
- Have husky produce a `.gitkeep` file and prompt users to commit it

**Comment by Stanzilla** [comment]
Still an issue, also often fails because cmd.exe can't use UNC paths and WSL uses that.

**Comment by typicode** [comment]
There seem to be multiple issues here. Some that I'm not sure can be fixed on husky's side like cmd.exe.
That said feel free to share if you've found workarounds or steps to reproduce the issue :)

The fix for the original issues would be to re-run `prepare` script which should have `husky install`. It will regenerate `_/husky.sh`.

I'm not aware of actions pruning `_` directory. Also many projects use lint-staged and there doesn't seem to be issues with `_/husky.sh`. I could be wrong but I'd suspect something else.

**Comment by ashraful-islam** [comment]
Hello!

We are facing this issue recently after upgrading from version `7.0.4` > `8.0.1`.
Reverting the version back to `7.0.4` fixes this issue.

The whole build script and components are exactly same,
but the husky version was bumped in a PR.
