### ISSUE TITLE
Husky + GitKraken = 💥

### ISSUE THREAD

**Issue by Siyfion** [typicode/husky#243]
So after adding Husky to my local project, all my local commits are now taking an eternity when using GitKraken. Note, I believe this issue is _specific_ to GitKraken, so it's unlikely that it's a Husky issue per-se, but it might be nice if the two teams had an issue in which to discuss getting it fixed?

I've spoken to the GitKraken team and given them as much information as possible (including giving them a link to this issue). But perhaps some of the Husky team might be able to give some pointers as to where to start looking for the cause?

**Comment by typicode** [comment]
Hi @Siyfion,

Hmm can't seem to reproduce, but I'm having a very simple hook:

```
  "husky": {
    "hooks": {
      "pre-commit": "echo fail && exit 1"
    }
  }
```

It takes 1 or 2 seconds to get the pre-commit failed message.
I've tried with GitKraken for Windows and husky `v0.15`.

Is it taking less time when you're commiting from the command-line?

**Comment by Siyfion** [comment]
Yep, way less time in both the CLI or when using Tower.

**Comment by Siyfion** [comment]
Oops didn’t mean to close

**Comment by Siyfion** [comment]
Oops, didn't mean to close.

**Comment by nloding** [comment]
I'm using Husky with commitlint and have the same issues with GitKraken. Additionally, GitKraken stops pushing to the remote. I've tried 0.14 and 0.15.0-rc.13, both have the same issue. I'm a GitKraken Pro user and have an active ticket with GitKraken regarding this. Hopefully they can issue a fix soon - I'm guessing it's an issue with GitKraken parsing the command output.

**Comment by emhagman** [comment]
This is also happening to me with latest husky and GitKraken with eslint in a pre-commit hook.

**Comment by nloding** [comment]
I've spoken with the GitKraken support team a few times now, and basically they've confirmed it doesn't work with husky and will won't put out any ETA on when it might. I _suspect_ but haven't tested that the issue is with node-git, which is what powers GitKraken.

**Comment by emhagman** [comment]
I've tested with a simple one line git hook and it still does not work for me. Something else is definitely going on.

**Comment by nloding** [comment]
I would report that to GitKraken support. They advertise support for standard git hooks, so definitely sounds broken.

**Comment by emhagman** [comment]
Yeah I am also in a long e-mail chain with them now 👎

**Comment by nloding** [comment]
Did you get anywhere with them? I'd love to know if there's progress on their end.

**Comment by emhagman** [comment]
Still talking to them. I'll keep you posted.

**Comment by emhagman** [comment]
I figured it out. At least for me. I use `fish` shell, not `bash`. Running GitKraken with the following (make sure it is closed) on OSX.

```
env SHELL=/bin/bash open -a "GitKraken"
```

Fixes the issue for me. Hooks now work, including `husky` hooks. I've let them know about the issue. For now, running that command is fine with me. If you aren't running `bash` as your default shell, give that command try.

**Comment by nloding** [comment]
Ain't that interesting. I'll give it a run. I'm using zsh at the moment.

**Comment by leinelissen** [comment]
I'm having this problem as well with zsh instead of fish. The command doesn't work for me however. Have you heard anything from GitKraken support @emhagman?

**Comment by emhagman** [comment]
@leinelissen They at least are aware of it and passed on what I have posted here to their team. If that command doesn't work, what I did to test my theory was create a new Mac user (which has "bash" by default) and try to use GitKraken there and it worked.

Maybe test that first and see? If it still doesn't work, you might be running into a different issue.

**Comment by patoncrispy** [comment]
Can confirm that @emhagman's solution resolved the issue for me using fish shell. I'm running tests before pushing code. In the future, once this is resolved, it would be cool to see some UI feedback of the husky hook progress somewhere!

**Comment by lusimail** [comment]
What version of node you guys are using?
I am using nvm and set the default as node 4. When I use GitKraken, it gives me the same error.

Then I tried setting the default as node 8, restart GitKraken, the error went away.

**Comment by railsstudent** [comment]
@lusimail  You are so smart, Lusia

**Comment by denishristov** [comment]
For any of you using fish you can try setting the custom terminal command to "cd %d; /bin/bash". You can find it under general in preferences.

**Comment by luchillo17** [comment]
This happens a lot with GitKraken in Windows, specially if i'm using WSL (Windows SubSystem Linux) as main shell, but setting the custom terminal command to the wsl.exe path didn't help at all.

**Comment by rlueder** [comment]
@douglasjunior I'm also using `oh-my-zsh` and this works for me:
```
$ SHELL=/bin/bash /snap/bin/gitkraken
```
(My version of GitKraken is from the Snap Store: https://snapcraft.io/gitkraken)

**Comment by tomtom44** [comment]
For me, on Windows, it wasn't the terminal used by GitKraken, 
It was the exit code that wasn't sent by my 'ng test'.
I added singleRun: true in karma.conf.js to run tests once and exit.

**Comment by lokers** [comment]
It happens to me as well, since the last update I made I think, previously all the hooks were working just fine.

**Comment by 555ea** [comment]
The hooks were not executing for me at all on Ubuntu 18.04 with GitKraken 5.0.4, but I've managed to make it work using the comments above and running it via `SHELL=/bin/bash /usr/bin/gitkraken`

**Comment by ancizararenas** [comment]
Also using Ubuntu 18.04 and GitRaken 5.0.4. Also facing same issues that pre-commit hooks are not running for me on my projects however when running via terminal as above it works for fine.

**Comment by Jakst** [comment]
Has anybody made progress on Windows?

**Comment by raphael-leger** [comment]
I have those blocking issues with Husky on GitKraken too.
My commands run well in a standard mac OS terminal as well as with zsh.

Setting `SHELL=/bin/bash ...` does **not** resolve the issue.

Specifically, I am using `react-testing-library` in some jest tests. When rendering an element with `render()` followed by a call to `waitForElement()`, the waited element never gets found, no matter how I increase jest tiemout. 

I found out that on the GitKraken Slack, 25th April 2019, the team said:
"GitKraken doesn't currently support husky git hooks. I'll upvote the existing feature request for it however :memo:"

**Comment by Jrenk** [comment]
I'm running `oh-my-zsh` on Ubuntu 18.04. When starting Gitkraken normally I get the following error when trying to commit changes:

[Error](https://imgur.com/7iw2leU)
[Hook Log](https://imgur.com/BD7o1F5)

When starting Gitkraken with `SHELL=/bin/bash /snap/bin/gitkraken` I get the following error:

[Error](https://imgur.com/zY2yMAD)
[Hook Log](https://imgur.com/2YAxZoY)

**Comment by Jrenk** [comment]
I solved this by not using the Gitkraken version installed by snap. Instead I installed the `.deb` file from https://www.gitkraken.com/

**Comment by JFGHT** [comment]
@Jrenk this fixed it for me. I'm not even using husky, just nvm.

**Comment by kayvanbree** [comment]
Nice issue title. 

I got the same problem using Windows 10 and GitKraken 6.0.0. People from my company wanna use Husky, but I don't want to use it just because it doesn't work in my favorite git client.

**Comment by typicode** [comment]
@kayvanbree I can't reproduce on Windows 10 and with GitKraken 6.0.0. It's working for me.

Can you try editing you .git/hooks/pre-commit and, as suggested by @emhagman, replace its content with a very basic Git hook:

```
#!/bin/sh
echo "test"
exit 1
```

Now try to make a commit, it should fail with a "test" message.

**Comment by eexe1** [comment]
After updating to Husky 3.0.0, it now works with GitKraken v6.0.0 on macOS.

**Comment by kayvanbree** [comment]
@typicode I just updated to 3.0.0, but still it fails on the pre-commit hook (I reinstalled the hooks by deleting them and running `npm install husky --save-dev`). It still fails. When I add the test hook it doesn't fail with a test message but with the following:

```
sh: C:\\Projects\\results-client\\.git\\hooks\\pre-commit: command not found
exit
```

It looks like it doesn't even run the file. The location is correct and the hook files are all being generated. I'm on Windows 10 v1903.

**Comment by typicode** [comment]
@kayvanbree Since the basic test hook fails, it seems like your installation has trouble running `sh` hooks (and therefore husky hooks too).

FWIW On Windows, I also have https://git-scm.com/ installed and no WSL. I suspect that default Git installation provides things needed to run Git hooks.

Can you try the following:
1. Install https://git-scm.com/ with default options
1. Restart GitKraken
1. Create `.git/hooks/pre-commit` with 
```
#!/bin/sh
echo "Hello from pre-commit"
exit 1
```
1. Try to commit using GitKraken

**Comment by kayvanbree** [comment]
@typicode I found out that my installation of GitKraken uses the Cygwin sh, which is quite unnecessary. 

![image](https://user-images.githubusercontent.com/11921540/61438064-e665ab80-a93e-11e9-9ef0-db26f75b1708.png)

I changed the path to `C:\Program Files\Git\bin\sh.exe` and it works now. The test fail works, and the Husky pre-commit hook actually ran. I tested running stylelint with errors and it actually returned exit code 2 with the errors. 

So, if anybody still has problems, check your path to sh.exe!

**Comment by typicode** [comment]
@kayvanbree thanks for the update!

**Comment by typicode** [comment]
Closing this issue as it "seems" most of the problem have been fixed or have a fix. Feel free to reopen or add a comments if there are other bugs.

To sum up:
- on Windows, proper path to `sh` need to be set and Git client need to be installed
- on Ubuntu, deb file works but not snap without an additional env variable
- on MacOS, I haven't tested, feedback welcome

**Comment by vidal7** [comment]
Why closing? I thought that the original issue was that local commits are taking an eternity when using GitKraken. This is exactly the issue I am experiencing right now.

**Comment by typicode** [comment]
@vidal7 sorry, since the issue was more than a year old, I wasn't sure if that was still the case with recent versions of GitKraken. Also other issues were mixed in (mostly Git hooks not running).

When I tested on Ubuntu/Windows, I didn't experience any slowness.
What's your OS and version of GitKraken?

**Comment by piotrwitek** [comment]
@typicode I also confirm that the original issue was unreasonably slow commits and it's still the case for me on macOS using ZSH shell.

**Comment by vidal7** [comment]
@typicode no problem. I can confirm that the slowness is still present. Having this simple git hook 

`
"husky": {
    "hooks": {
      "pre-commit": "echo fail && exit 1"
    }
  }
`

takes twice the time to execute with GitKraken than to execute with the command line. I have Windows 10, GitKraken 6.0.1 and Husky 3.0.2.

**Comment by typicode** [comment]
Thanks for the details.

In GitKraken preferences, can you check that it points to the `sh.exe` that comes with https://git-scm.com/ and not some other `sh.exe` that may be slower.

See https://github.com/typicode/husky/issues/243#issuecomment-512709974

**Comment by raphael-leger** [comment]
The issue is still current. Re-open it?

> on MacOS, I haven't tested, feedback welcome

cf. https://github.com/typicode/husky/issues/243#issuecomment-491731550
None of the solutions of this thread did a difference.

**Comment by typicode** [comment]
@raphael-leger does your jest tests run but just fail to find the React element or they don't run at all? Can you make a commit with HUSKY_DEBUG=1 in GitKraken and paste the output?

**Comment by vidal7** [comment]
> Thanks for the details.
> 
> @piotrwitek @vidal7 In GitKraken preferences, can you check that it points to the `sh.exe` that comes with https://git-scm.com/ and not some other `sh.exe` that may be slower.
> 
> See [#243 (comment)](https://github.com/typicode/husky/issues/243#issuecomment-512709974)

@typicode yes, it is pointing to git that comes with https://git-scm.com/

**Comment by typicode** [comment]
@vidal7 I must admit I'm running out of ideas :/ sorry. (FWIW) On Windows, I did the test with https://git-scm.com/ https://nodejs.org/en/ and GitKraken... I don't know why there's a difference  between speed in the terminal and the GUI client.

**Comment by piotrwitek** [comment]
@typicode Thanks but I'm running macOS, not Windows as I have written. There is no such option.

**Comment by typicode** [comment]
@piotrwitek you're right my bad. I don't have a mac so I can't test directly. Is it also slow if you create a new project like this:

```sh
mkdir foo
cd foo
git init
```

create `.git/hooks/pre-commit`

```sh
#!/bin/sh
echo "Hello from pre-commit"
exit 1
```

```sh
chmod +x .git/hooks/pre-commit
```

And do a test commit

**Comment by piotrwitek** [comment]
@typicode thanks for the instructions, I did some testing and it feels that the delay is the same for manual pre-commit hooks as for husky. So I guess that might be an issue related to GitKraken + zsh shell in my case.

**Comment by nora-white** [comment]
I've been following this issue for several weeks and **being unable to push with GitKraken and Husky** is still an issue for myself and several people on my team (all with Macs).

I've attempted to open GitKraken via Fish shell as other threads have suggested, but that doesn't work either. I'm running the latest version of Git (2.22.0) and GitKraken (6.1.1). I've tried changing the custom terminal command as well as @denishristov suggested, but that doesn't fix the problem. This has become such an issue for our team that we are now considering finding an alternative to Husky. For now, we have been pushing via terminal and still using GitKraken for the remainder of all git tasks.

**Comment by KevinDenys** [comment]
Same issue here, gitkraken version 6.1.4 on mac. Tested using env SHELL=/bin/bash open -a "GitKraken"

Commiting using the Iterm2 terminal with zsh is no problem..

**Comment by KevinDenys** [comment]
Seems to be working on Gitkraken version 6.2.0 on mac without doing any shell changes

**Comment by elucidsoft** [comment]
I can attest, the Snap version is complete garbage. It's not surprising really, pretty much every single application I have used that was a snap is complete garbage. It's probably the worst thing that's ever happened to Linux.

**Comment by kinjoyuya1219** [comment]
fixed!

```
env SHELL=/bin/bash open -a "GitKraken"
```

fish: 3.0.2
Gitkraken: 6.3.1
husky: 3.1.0

thank you.

**Comment by 0xClpz** [comment]
For anyone stumbling across this issue, here's how I fixed it.

I installed node using asdf (node v12) and realised I still had node installed in brew (v13)  and gitkraken was using the version provided by brew.

Running the command below fixed it for me
```
brew uninstall --ignore-dependencies node
```

**Comment by fernandofranca** [comment]
An alternative is to add this alias to your .zshrc or .bashrc
`alias gitk='SHELL=/bin/bash nohup /Applications/GitKraken.app/Contents/MacOS/GitKraken > /dev/null&'`

**Comment by Pacheco95** [comment]
> I solved this by not using the Gitkraken version installed by snap. Instead I installed the `.deb` file from https://www.gitkraken.com/

Worked for me too. Thank you

**Comment by adongnmh** [comment]
Anyone getting this to work with zsh on MacOS Big Sur?

**Comment by mnlttt** [comment]
> Anyone getting this to work with zsh on MacOS Big Sur?

zsh and Big Sur here too, tried with [pre-commit](https://www.npmjs.com/package/pre-commit) too and it gave me a more meaningful log:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../lib/cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the `lint:ts`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit: 
Hook process exited.
```

None of the suggested solutions work.

**Comment by priverop** [comment]
I found a workaround for Gitkraken and Husky 5: https://gist.github.com/priverop/80fb9ffe7930ebc003146b8b4fca7af5

**Comment by slaby93** [comment]
For anyone looking for answer for Linux:
```
sudo nvim .bashrc
alias gitkraken='SHELL=/bin/bash gitkraken'
```

**Comment by xRiot** [comment]
I struggled with the same issue on MacOS and Debian 11 Bullseye. Here's how I solved it!

**Linux**
As it turned out Gitkraken wasn't using my exports from `~/.bashrc`, it defaulted to `~/.profile`. Because of this my hooks complained about `Yarn requires Node.js 4.0 or higher to be installed`. I grabbed the required exports from manual git installation instructions (https://github.com/nvm-sh/nvm#git-install) and pasted them into `~/.profile`.

**MacOS**
Kudos to @0xClpz
```zsh
brew uninstall --ignore-dependencies node
```

**Comment by vidal7** [comment]
Is someone managed to fix this issue on Windows 10? I am still experiencing this issue on Windows 10 and GitKraken 7.5.1

**Comment by mnlttt** [comment]
Why is this setting missing on MacOS? I think it could solve the problem, so I'll contact the GitKraken team about it.

<img width="570" alt="CleanShot 2021-05-03 at 11 04 32@2x" src="https://user-images.githubusercontent.com/37709016/116858940-7ef61a00-abff-11eb-88dc-41ec0f0e7a0b.png">

**Comment by notmedia** [comment]
@mnlttt Do you have any news from Gitkraken support?

**Comment by mnlttt** [comment]
Nope, they're ignoring me because I'm not a Pro customer, just someone on an Individual plan.

**Comment by notmedia** [comment]
I'm with pro account, sent them a message.

**Comment by mnlttt** [comment]
@notmedia are they ignoring you too?

**Comment by notmedia** [comment]
@mnlttt Unfortunately yes :(

**Comment by mnlttt** [comment]
@notmedia well that's ridiculous, the Pro plan includes a GUARANTEED reply. I'm reconsidering being a customer of them.

**Comment by priverop** [comment]
I contacted them a while ago suggesting that we could parametrize the "git-hooks-path" of the repo. They replied to me that they already had that in mind, and they will do it.

**Comment by mnlttt** [comment]
So we’re missing a critical feature and we don’t know when we’ll get it, nice.

**Comment by michelson** [comment]
nvm/husky does not work with gitkraken :(

**Comment by andorfermichael** [comment]
see also https://github.com/typicode/husky/issues/875

**Comment by nora-white** [comment]
> Create the file `~/.huskyrc`
> 
> ```
> #!/usr/bin/env bash
> 
> source ~/.bash_profile
> 
> export NVM_DIR="$HOME/.nvm"
> [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
> 
> if test -f ".nvmrc"; then
>     nvm use
> fi
> ```
> 
> Credits: [#77 (comment)](https://github.com/typicode/husky/issues/77#issuecomment-630065185)

I ended up back in this thread 3 years after I initially commented on it and finally there is a solution that worked for me! @Luc45 thank you!

**Comment by webel** [comment]
So frigging tired of this, I keep coming back every couple of weeks since 3 months thinking I must have missed something. Tried everything I can see in this thread relevant to mac/linux. Opening from terminal with env set (both bash, zsh, and in rosetta mode and native arm), removing any node that's not installed by nvm, adding the ~/.huskyrc.

**Comment by larrykkk** [comment]
> Create the file `~/.huskyrc`
> 
> ```
> #!/usr/bin/env bash
> 
> source ~/.bash_profile
> 
> export NVM_DIR="$HOME/.nvm"
> [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
> 
> if test -f ".nvmrc"; then
>     nvm use
> fi
> ```
> 
> Credits: [#77 (comment)](https://github.com/typicode/husky/issues/77#issuecomment-630065185)

for people using zsh as default shell
just change source ~/.bash_profile to source ~/.zshrc
work to me

**Comment by wnz99** [comment]
> For me it worked when I changed the default terminal on Gitkraken to `iTerm2` but I guess you can change it to whatever you use.
> 
> Preferences -> General -> Default Terminal Dropdown
> 
> <img alt="Screenshot 2022-06-15 at 11 01 27" width="1267" src="https://user-images.githubusercontent.com/35957481/173801770-57dfde73-6e13-48d4-83f9-b284fa738fd4.png">

This worked for me.

**Comment by fadomire** [comment]
I've solved it by installing last husky version 9
and following this solution on their doc:
https://typicode.github.io/husky/how-to.html#solution

```
# ~/.config/husky/init.sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
```
